# This is not intended to represent any kind of useful OpenTelemetry
# Collector configuration, or to demonstrate how to configure any
# particular component. Its purpose is simply to test that all
# referenced components are present in the built collector.

extensions:
  memory_ballast:
  zpages:
  health_check:
  pprof:
  oauth2client:
    client_id: someclientid
    client_secret: someclientsecret
    token_url: https://example.com/oauth2/default/v1/token

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: localhost:4318
  jaeger:
    protocols:
      grpc:
  opencensus:
  zipkin:

processors:
  batch:
  memory_limiter:
    limit_mib: 1536
    check_interval: 5s
  attributes:
    actions:
      - key: test_attribute
        value: true
        action: insert
  resource:
    attributes:
      - key: test_resource
        value: true
        action: insert
  span:
    status:
      code: Ok

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: otelcol2:4317
  otlphttp:
    endpoint: https://example.com:4318/v1/traces
  jaeger:
    endpoint: jaeger-all-in-one:14250

service:
  extensions: [memory_ballast, zpages, health_check, pprof, oauth2client]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, jaeger, opencensus, zipkin]
      processors: [memory_limiter, batch, attributes, resource, span]
      exporters: [logging, otlp, otlphttp, jaeger]
